### ISSUE TITLE
Use a struct directly, not as a pointer

### ISSUE THREAD

**Issue by rabbiveesh** [Perl5-FFI/FFI-Platypus#180] opened 2019-09-13 13:32 UTC
I'm trying to make an FFI interface for libpostal (because Geo::libpostal is out of date, and XS is making my head explode). I'm running into an issue because I need to map the `bool` type from `stdbool.h`, but I can't get perl to not explode on basic usage.

I've tried using 'bool' as a type (and then realized it doesn't exist). Then I tried char, int, uint8, sint8, which are mentioned in various places as alternatives, but it still isn't working.

What's the recommended way to use the `bool` type?

**Comment by plicease** [comment] 2019-09-13 14:24
hrm.  bool is platform dependent so you can't portablely use `char` or `int`, etc. (although it could be either).  Platypus does probe for `bool` when it is installed so you should be able to use it:

```
% perl -MFFI::Platypus -MYAML= -E 'say Dump(FFI::Platypus->type_meta("bool"))'
---
element_size: 1
element_type: int
ffi_type: uint8
sign: 0
size: 1
type: scalar
type_code: 33
```

However if the detection logic fails then you don't get the type.  What platform are you using?  The `config.log` file from the `FFI-Platypus` install might provide some clues if it isn't able to probe it.

Also: (this probably isn't it since you mentioned using `int` and `char`), but you only get `bool` if lang is C (which is the default).

If you have a concise example that demonstrates your issue I might be able to help diagnose the problem.

**Comment by rabbiveesh** [comment] 2019-09-13 14:27
It's almost the Sabbath, so I'll post my example tomorrow night.
I'm on Ubuntu 16.04 64bit.

**Comment by rabbiveesh** [comment] 2019-09-15 11:03
Yeah, So i'm getting the right output then, so this must not be the problem. Lemme post what I'm trying to do, and then we'll see what the issue is:
I'm trying to get this struct:
```c
typedef struct libpostal_near_dupe_hash_options {
    bool with_name;
    bool with_address;
    bool with_unit;
    bool with_city_or_equivalent;
    bool with_small_containing_boundaries;
    bool with_postal_code;
    bool with_latlon;
    double latitude;
    double longitude;
    uint32_t geohash_precision;
    bool name_and_address_keys;
    bool name_only_keys;
    bool address_only_keys;
} libpostal_near_dupe_hash_options_t;
```
Which is returns these defaults from the following function:
```c
static libpostal_near_dupe_hash_options_t LIBPOSTAL_NEAR_DUPE_HASH_DEFAULT_OPTIONS = {
    .with_name = true,
    .with_address = true,
    .with_unit = false,
    .with_city_or_equivalent = true,
    .with_small_containing_boundaries = true,
    .with_postal_code = true,
    .with_latlon = false,
    .latitude = 0.0,
    .longitude = 0.0,
    .geohash_precision = DEFAULT_NEAR_DUPE_GEOHASH_PRECISION,
    .name_and_address_keys = true,
    .name_only_keys = false,
    .address_only_keys = false
};

libpostal_near_dupe_hash_options_t libpostal_get_near_dupe_hash_default_options(void) {
    return LIBPOSTAL_NEAR_DUPE_HASH_DEFAULT_OPTIONS;
}
```

And I'm using this code:
```perl
package Hashes::Options;
use FFI::Platypus::Record;

record_layout( qw/
    bool with_name
    bool with_address
    bool with_unit
    bool with_city_or_equivalent
    bool with_small_containing_boundaries
    bool with_postal_code
    bool with_latlon
    double latitude
    double longitude
    uint32 geohash_precision
    bool name_and_address_keys
    bool name_only_keys
    bool address_only_keys
/);



package main;
use FFI::Platypus;


my $ffi = FFI::Platypus->new;
$ffi->lib('libpostal.so');
$ffi->type("record(Hashes::Options)" => 'hash_options');

$ffi->attach( 
  [ libpostal_get_near_dupe_hash_default_options =>
    'hash_defaults' ], 
  [], 'hash_options');
```
Which gives me the following error:
```
Attempt to free unreferenced scalar: SV 0x31ab0e8, Perl interpreter: 0x276a010 at /home/veesh/perl5/lib/perl5/Reply.pm line 217.
fish: “./ffitry” terminated by signal SIGSEGV (Address boundary error)
[I] ~ [139] $
```

I'm not sure at all what's going on there.

**Comment by rabbiveesh** [comment] 2019-09-15 11:34
Okay, I got this. I think the issue is that FFI::Platypus assumes that records are pointers (at least that's what happened when i looked at the type_meta for my Hashes::Options record:
```perl
0> $ffi->type_meta('hash_options')
$res[0] = \ {
    ffi_type    "pointer",
    ref         1,
    size        31,
    type        "record",
    type_code   2308
}
```
And the code I'm connecting to wants it as an actual value. How do I work around that?

**Comment by plicease** [comment] 2019-09-15 15:44
Record values are now supported with the new type parser.  You need a fairly recent version of Platypus.  When you create the Platypus instance:

```
my $ffi = FFI::Platypus->new( api => 1 );
$ffi->type("record(Hashes::Options)" => 'hash_options');
```

Now `hash_options` is a record pass-by-value and `hash_options*` is a pointer to a record.

The interface is experimental but should be promoted in the near future.  (probably not more than a few weeks).  It's been used internally by Platypus for quite some time now, and just needs some testing.  Writing the bindings for libpostal would speed this up if we can get a positive result.

It issues a fairly noisy warning so that we can change the API before it is declared non-experimental (tbh I'm not sure that we will change it much at this point), but you can turn off the warning using the internal `experimental` key:

```
my $ffi = FFI::Platypus->new( api => 1, experimental => 1 );
```

I just ask that you not cpan anything that uses the `experimental` key as it defeats the purpose.

**Comment by plicease** [comment] 2019-09-15 15:46
This is a duplicate of #57 ... might be worth keeping this open though until the new API is non-experimental.

**Comment by rabbiveesh** [comment] 2019-09-16 04:55
Should I reply here with any more problems I have, or make a new issue?

**Comment by plicease** [comment] 2019-09-16 12:56
new issue unless it is related to this.

**Comment by plicease** [comment] 2019-11-16 13:59
With 1.00 out, the features required here are no longer experimental and available as a prod release :tada:

**Closed by plicease** 2019-11-16 13:59 UTC
Labels: 🥓Duplicate
