### ISSUE TITLE
Segmentation fault in libclang.so

### ISSUE THREAD

**Issue by azawawi** [Perl5-FFI/FFI-Platypus#92] opened 2018-11-21 20:55 UTC
Thanks for your awesome module. I just started out using it today. Overall it is as good as Perl 6's NativeCall with it being way faster.

However, I encountered this strange segmentation fault. Is it related to 'Records not passing by value todo'?
https://github.com/azawawi/scripts/blob/master/clang.pl#L93

Please let me know if I am using it correctly or not? Any pro tips would be welcomed. Thanks :+1: 

Note: I am using Ubuntu 18.04 with 0.58 `FFI::Platypus`.

I guess it is related to https://github.com/Perl5-FFI/FFI-Platypus/issues/57.

See also:
- [clang's Index.h](https://clang.llvm.org/doxygen/Index_8h_source.html).

**Comment by plicease** [comment] 2018-11-21 21:09
I didn't find the declaration for `CXTranslationUnit`, but if that is a struct being passed in as a struct and  not a pointer to a struct then it probably is related to #57, we currently do not support that unfortunately, and I am not sure tbh when I will have time to work on that.  I've done a major restructuring of the internal type system that should make it possible but somebody has to actually go into the code and make it work.

**Comment by azawawi** [comment] 2018-11-22 12:46
So how can i help? :smile: Where should i start?

I looked up similar work in Ruby land.

- `CXCursor` C Struct
https://github.com/ioquatix/ffi-clang/blob/master/lib/ffi/clang/lib/cursor.rb#L206

- Return type: `CXCursor.by_value` (C Struct) from `clang_getTranslationUnitCursor`.
https://github.com/ioquatix/ffi-clang/blob/master/lib/ffi/clang/lib/cursor.rb#L279  

- Return type: `CXTranslationUnit` (an alias to a pointer).
https://github.com/ioquatix/ffi-clang/blob/master/lib/ffi/clang/lib/translation_unit.rb#L90

After commenting `clang_getTranslationUnitCursor`, no segmentation fault occurs after several runs.

**Comment by plicease** [comment] 2019-01-01 10:32
I believe this should be a duplicate of #57 and related to #89, so I will be tracking this issue there.  I'm working on implementing a number of new types atm and hope to get to this soon.

**Closed by plicease** 2019-01-01 10:32 UTC
Labels: duplicate

**Comment by plicease** [comment] 2019-07-12 21:49
update: Pass-by-value records is now implemented in the PR #135 that I hope to merge soon.
